package com.encore.playground.global.api;

public class ResponseMessage {
    public static final String LOGIN_SUCCESS = "LOGIN_SUCCESS";
    public static final String LOGIN_FAIL = "LOGIN_FAIL";
    public static final String INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
    public static final String READ_USER = "READ_USER";
    public static final String NOT_FOUND_USER = "NOT_FOUND_USER";
    public static final String REGISTER_USER = "REGISTER_USER";
    public static final String UPDATE_USER = "UPDATE_USER";
    public static final String UNREGISTER_USER = "UNREGISTER_USER";
    public static final String LOG_OUT = "LOG_OUT";
    public static final String ACCESS_TOKEN_EXPIRED = "ACCESS TOKEN EXPIRED";
    public static final String ANSWER_MODIFY_SUCCESS = "ANSWER_MODIFIED_SUCCESS";
    public static final String ANSWER_MODIFY_FAILED = "ANSWER_MODIFIED_FAILED";
    public static final String ANSWER_DELETE_SUCCESS = "ANSWER_DELETE_SUCCESS";
    public static final String ANSWER_DELETE_FAILED = "ANSWER_DELETE_FAILED";
    public static final String QNA_WRITE_SUCCESS = "QNA_WRITE_SUCCESS";
    public static final String QNA_VIEW_SUCCESS = "QNA_VIEW_SUCCESS";
    public static final String QNA_MODIFY_SUCCESS = "QNA_MODIFY_SUCCESS";
    public static final String QNA_MODIFY_FAILED = "QNA_MODIFY_FAILED";
    public static final String QNA_MODIFY_ACCESS = "QNA_MODIFY_ACCESS";
    public static final String QNA_DELETE_SUCCESS = "QNA_DELETE_SUCCESS";
    public static final String QNA_DELETE_FAILED = "QNA_DELETE_FAILED";
    public static final String FEED_DELETE_SUCCESS = "FEED_DELETE_SUCCESS";
    public static final String FEED_DELETE_FAILED = "FEED_DELETE_FAILED";
    public static final String FEED_MODIFY_SUCCESS = "FEED_MODIFY_SUCCESS";
    public static final String FEED_MODIFY_FAILED = "FEED_MODIFY_FAILED";
    public static final String COMMENT_DELETE = "COMMENT_DELETE";
    public static final String COMMENT_DELETE_FAILED = "COMMENT_DELETE_FAILED";
    public static final String COMMENT_MODIFY = "COMMENT_MODIFY";
    public static final String COMMENT_MODIFY_FAILED = "COMMENT_MODIFY_FAILED";
    public static final String NOTICE_ADMIN_ACCESS = "NOTICE_ADMIN_ACCESS";
    public static final String NOTICE_USER_ACCESS = "NOTICE_USER_ACCESS";
    public static final String NOTICE_WRITER_ACCESS = "NOTICE_WRITER_ACCESS";
    public static final String NOTICE_WRITER_ACCESS_FAILED ="NOTICE_WRITER_ACCESS_FAILED";
    public static final String NOTICE_DELETE_SUCCESS = "NOTICE_DELETE_SUCCESS";
    public static final String NOTICE_DELETE_FAILED = "NOTICE_DELETE_FAILED";
    public static final String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static final String DB_ERROR = "DB_ERROR";
    public static final String QUESTION_WRITER_ACCESS = "QUESTION_WRITER_ACCESS";
    public static final String QUESTION_WRITER_ACCESS_FAILED = "QUESTION_WRITER_ACCESS_FAILED";
    public static final String FEED_DETAIL_SUCCESS = "FEED_DETAIL_SUCCESS";
    public static final String FEED_DETAIL_FAILED = "FEED_DETAIL_FAILED";
    public static final String USERID_EXIST = "USERID_EXIST";
    public static final String USERID_USEABLE = "USERID_USEABLE";
}
